/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofincurso;

/**
 *
 * @author DAW
 */
public class Cliente extends javax.swing.JFrame {
    
    
    public Cliente() {
        setLocation(800,400);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PedServ = new javax.swing.JButton();
        MisServ = new javax.swing.JButton();
        URL = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Bienvenido estimado Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        PedServ.setText("Pedir servicio");
        PedServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedServActionPerformed(evt);
            }
        });
        getContentPane().add(PedServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        MisServ.setText("Mis servicios");
        MisServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MisServActionPerformed(evt);
            }
        });
        getContentPane().add(MisServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        URL.setText("Sobre nosotros");
        URL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URLActionPerformed(evt);
            }
        });
        getContentPane().add(URL, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        CSesion.setText("Cerrar Sesion");
        CSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSesionActionPerformed(evt);
            }
        });
        getContentPane().add(CSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PedServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedServActionPerformed
        dispose();
        Pedir_servicio PS=new Pedir_servicio();
        PS.setVisible(true);
    }//GEN-LAST:event_PedServActionPerformed

    private void MisServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MisServActionPerformed
        dispose();
        Mis_servicios MS=new Mis_servicios();
        MS.setVisible(true);
    }//GEN-LAST:event_MisServActionPerformed

    private void URLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URLActionPerformed

    private void CSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSesionActionPerformed
        dispose();
        Inicio i=new Inicio();
        i.setVisible(true);
    }//GEN-LAST:event_CSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CSesion;
    private javax.swing.JButton MisServ;
    private javax.swing.JButton PedServ;
    private javax.swing.JButton URL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
