/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofincurso;

import java.awt.Dimension;
import proyectofincurso.clases.ConectBD;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.*;
import proyectofincurso.clases.UsuarioConectado;

/**
 *
 * @author DAW
 */
public class Mis_servicios extends javax.swing.JFrame {
    DefaultTableModel mod=new DefaultTableModel();
    /**
     * Creates new form Mis_servicios
     */
    public Mis_servicios() {
        
        setLocation(800,400);
        initComponents();
        try{
            String id,E,F,H,T;
            int idn;
            
            Connection c = ConectBD.Conexion();
            
            int idU=UsuarioConectado.idU;
            idU=1;
             
            String titulosC[]={"Servicio","Establecimiento","Fecha","Hora","Trabajos"};
            mod.setColumnIdentifiers(titulosC);
            Tabla.setModel(mod);
            Tabla.setPreferredScrollableViewportSize(new Dimension(700, 150));
            
            String sql="SELECT s.id_servicio,e.direccion,s.fecha_inicio,s.hora_inicio,t.nombre FROM servicios s\n" +
                        "JOIN establecimientos e ON s.id_establecimiento = e.id_establecimiento\n" +
                        "JOIN labores l ON s.id_servicio = l.id_servicio\n" +
                        "JOIN trabajos t ON l.id_trabajo = t.id_trabajo\n" +
                        "WHERE s.id_cliente ="+idU+";";                
            Statement s= c.createStatement();
            ResultSet a= s.executeQuery(sql);
            
            while (a.next()){
                idn=a.getInt(1);
                id=Integer.toString(idn);
                E=a.getString(2);
                F=a.getString(3);
                H=a.getString(4);
                T=a.getString(5);
                String row[]={id,E,F,H,T};
                mod.addRow(row);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "error en la BD");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ScrollTabla = new javax.swing.JScrollPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Hora = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EstablecimientosAñadir = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        EstablecimientosAñadidos = new javax.swing.JList<>();
        AñadEstab = new javax.swing.JButton();
        ElimEstab = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        CB1Hora = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        CB2Hora = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        Dia1 = new javax.swing.JComboBox<>();
        Mes1 = new javax.swing.JComboBox<>();
        Año1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Dia2 = new javax.swing.JComboBox<>();
        Mes2 = new javax.swing.JComboBox<>();
        Año2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        EstablecimientosAñadir1 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        EstablecimientosAñadidos1 = new javax.swing.JList<>();
        AñadTrab = new javax.swing.JButton();
        ElimTrab = new javax.swing.JButton();
        btnFiltrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Mis servicios");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(Tabla);

        ScrollTabla.setViewportView(jScrollPane7);

        jTabbedPane1.addTab("Servicios", ScrollTabla);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportView(EstablecimientosAñadir);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 140, 160));

        jScrollPane3.setViewportView(EstablecimientosAñadidos);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 140, 160));

        AñadEstab.setText("añadir");
        AñadEstab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadEstabActionPerformed(evt);
            }
        });
        jPanel3.add(AñadEstab, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        ElimEstab.setText("eliminar");
        ElimEstab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElimEstabActionPerformed(evt);
            }
        });
        jPanel3.add(ElimEstab, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 80, -1));

        Hora.addTab("Establecimientos", jPanel3);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CB1Hora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CB1Hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00  ", "00:30  ", "01:00  ", "01:30  ", "02:00  ", "02:30  ", "03:00  ", "03:30  ", "04:00  ", "04:30  ", "05:00  ", "05:30  ", "06:00  ", "06:30  ", "07:00  ", "07:30  ", "08:00  ", "08:30  ", "09:00  ", "09:30  ", "10:00  ", "10:30  ", "11:00  ", "11:30  ", "12:00  ", "12:30  ", "13:00  ", "13:30  ", "14:00  ", "14:30  ", "15:00  ", "15:30  ", "16:00  ", "16:30  ", "17:00  ", "17:30  ", "18:00  ", "18:30  ", "19:00  ", "19:30  ", "20:00  ", "20:30  ", "21:00  ", "21:30  ", "22:00  ", "22:30  ", "23:00  ", "23:30  ", "24:00" }));
        jPanel5.add(CB1Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 90, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Entre las                            y");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 20));

        CB2Hora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CB2Hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00  ", "00:30  ", "01:00  ", "01:30  ", "02:00  ", "02:30  ", "03:00  ", "03:30  ", "04:00  ", "04:30  ", "05:00  ", "05:30  ", "06:00  ", "06:30  ", "07:00  ", "07:30  ", "08:00  ", "08:30  ", "09:00  ", "09:30  ", "10:00  ", "10:30  ", "11:00  ", "11:30  ", "12:00  ", "12:30  ", "13:00  ", "13:30  ", "14:00  ", "14:30  ", "15:00  ", "15:30  ", "16:00  ", "16:30  ", "17:00  ", "17:30  ", "18:00  ", "18:30  ", "19:00  ", "19:30  ", "20:00  ", "20:30  ", "21:00  ", "21:30  ", "22:00  ", "22:30  ", "23:00  ", "23:30  ", "24:00" }));
        jPanel5.add(CB2Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 90, 30));

        Hora.addTab("Hora", jPanel5);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Dia>", "1  ", "2  ", "3  ", "4  ", "5  ", "6  ", "7  ", "8  ", "9  ", "10  ", "11  ", "12  ", "13  ", "14  ", "15  ", "16  ", "17  ", "18  ", "19  ", "20  ", "21  ", "22  ", "23  ", "24  ", "25  ", "26  ", "27  ", "28  ", "29  ", "30  ", "31" }));
        Dia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dia1ActionPerformed(evt);
            }
        });
        jPanel6.add(Dia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        Mes1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Mes>", "Enero  ", "Febrero  ", "Marzo  ", "Abril  ", "Mayo  ", "Junio  ", "Julio  ", "Agosto  ", "Septiembre  ", "Octubre  ", "Noviembre  ", "Diciembre" }));
        jPanel6.add(Mes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        Año1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Año>", "2025  ", "2026  ", "2027  ", "2028  ", "2029  ", "2030  ", "2031  ", "2032  ", "2033  ", "2034  ", "2035  ", "2036  ", "2037  ", "2038  ", "2039  ", "2040  ", "2041  ", "2042  ", "2043  ", "2044  ", "2045  ", "2046  ", "2047  ", "2048  ", "2049  ", "2050" }));
        jPanel6.add(Año1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Del");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("de");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("de");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        Dia2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Dia>", "1  ", "2  ", "3  ", "4  ", "5  ", "6  ", "7  ", "8  ", "9  ", "10  ", "11  ", "12  ", "13  ", "14  ", "15  ", "16  ", "17  ", "18  ", "19  ", "20  ", "21  ", "22  ", "23  ", "24  ", "25  ", "26  ", "27  ", "28  ", "29  ", "30  ", "31" }));
        Dia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dia2ActionPerformed(evt);
            }
        });
        jPanel6.add(Dia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        Mes2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Mes>", "Enero  ", "Febrero  ", "Marzo  ", "Abril  ", "Mayo  ", "Junio  ", "Julio  ", "Agosto  ", "Septiembre  ", "Octubre  ", "Noviembre  ", "Diciembre" }));
        jPanel6.add(Mes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        Año2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Año>", "2025  ", "2026  ", "2027  ", "2028  ", "2029  ", "2030  ", "2031  ", "2032  ", "2033  ", "2034  ", "2035  ", "2036  ", "2037  ", "2038  ", "2039  ", "2040  ", "2041  ", "2042  ", "2043  ", "2044  ", "2045  ", "2046  ", "2047  ", "2048  ", "2049  ", "2050" }));
        jPanel6.add(Año2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("de");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("de");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Hasta el");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        Hora.addTab("Fecha", jPanel6);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setViewportView(EstablecimientosAñadir1);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 140, 160));

        jScrollPane5.setViewportView(EstablecimientosAñadidos1);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 140, 160));

        AñadTrab.setText("añadir");
        AñadTrab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadTrabActionPerformed(evt);
            }
        });
        jPanel4.add(AñadTrab, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        ElimTrab.setText("eliminar");
        ElimTrab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElimTrabActionPerformed(evt);
            }
        });
        jPanel4.add(ElimTrab, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        Hora.addTab("Trabajos", jPanel4);

        jTabbedPane1.addTab("Filtros", Hora);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 600, 300));

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        dispose();
        Cliente C=new Cliente();
        C.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void ElimTrabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElimTrabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ElimTrabActionPerformed

    private void AñadTrabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadTrabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñadTrabActionPerformed

    private void Dia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dia2ActionPerformed

    private void Dia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dia1ActionPerformed

    private void ElimEstabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElimEstabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ElimEstabActionPerformed

    private void AñadEstabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadEstabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AñadEstabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mis_servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mis_servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mis_servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mis_servicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mis_servicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadEstab;
    private javax.swing.JButton AñadTrab;
    private javax.swing.JComboBox<String> Año1;
    private javax.swing.JComboBox<String> Año2;
    private javax.swing.JComboBox<String> CB1Hora;
    private javax.swing.JComboBox<String> CB2Hora;
    private javax.swing.JComboBox<String> Dia1;
    private javax.swing.JComboBox<String> Dia2;
    private javax.swing.JButton ElimEstab;
    private javax.swing.JButton ElimTrab;
    private javax.swing.JList<String> EstablecimientosAñadidos;
    private javax.swing.JList<String> EstablecimientosAñadidos1;
    private javax.swing.JList<String> EstablecimientosAñadir;
    private javax.swing.JList<String> EstablecimientosAñadir1;
    private javax.swing.JTabbedPane Hora;
    private javax.swing.JComboBox<String> Mes1;
    private javax.swing.JComboBox<String> Mes2;
    private javax.swing.JScrollPane ScrollTabla;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
