/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofincurso;

import java.sql.*;
import javax.swing.*;
import proyectofincurso.clases.ConectBD;
import proyectofincurso.clases.UsuarioConectado;

/**
 *
 * @author DAW
 */
public class Pedir_servicio extends javax.swing.JFrame {
    private DefaultListModel añadList= new DefaultListModel();
    private DefaultListModel obList= new DefaultListModel();
    
    /**
     * Creates new form Pedir_servicio
     */
    public Pedir_servicio() {
        setLocation(800,400);
        initComponents();
        ListTrab1.setModel(añadList);
        Listrab2.setModel(obList);
        try{
            Connection c = ConectBD.Conexion();
            
            int idU=UsuarioConectado.idU;
            idU=1;
            
            Estab.removeAllItems();
            //establecimientos
            String sql="SELECT direccion from establecimientos WHERE id_cliente="+idU+";";
            Statement s= c.createStatement();
            ResultSet a= s.executeQuery(sql);
            
            while (a.next()){
                Estab.addItem(""+a.getString(1)+"");
            }
            
            //trabajos
            sql="SELECT nombre FROM trabajos;";
            s= c.createStatement();
            a= s.executeQuery(sql);
            
            while(a.next()){
                Object Trab=a.getString(1);
                añadList.addElement(Trab);
            }   
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "error en la base de datos");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        EnvServicio = new javax.swing.JButton();
        Dia = new javax.swing.JComboBox<>();
        Mes = new javax.swing.JComboBox<>();
        Año = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Hora = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Listrab2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListTrab1 = new javax.swing.JList<>();
        ElimTrab = new javax.swing.JButton();
        AñadEstab = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Estab = new javax.swing.JComboBox<>();
        AñadTrab1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pedir servicio");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        EnvServicio.setText("Enviar");
        getContentPane().add(EnvServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 90, 30));

        Dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Dia>", "1  ", "2  ", "3  ", "4  ", "5  ", "6  ", "7  ", "8  ", "9  ", "10  ", "11  ", "12  ", "13  ", "14  ", "15  ", "16  ", "17  ", "18  ", "19  ", "20  ", "21  ", "22  ", "23  ", "24  ", "25  ", "26  ", "27  ", "28  ", "29  ", "30  ", "31" }));
        Dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaActionPerformed(evt);
            }
        });
        getContentPane().add(Dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Mes>", "Enero  ", "Febrero  ", "Marzo  ", "Abril  ", "Mayo  ", "Junio  ", "Julio  ", "Agosto  ", "Septiembre  ", "Octubre  ", "Noviembre  ", "Diciembre" }));
        getContentPane().add(Mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        Año.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Año>", "2025  ", "2026  ", "2027  ", "2028  ", "2029  ", "2030  ", "2031  ", "2032  ", "2033  ", "2034  ", "2035  ", "2036  ", "2037  ", "2038  ", "2039  ", "2040  ", "2041  ", "2042  ", "2043  ", "2044  ", "2045  ", "2046  ", "2047  ", "2048  ", "2049  ", "2050" }));
        getContentPane().add(Año, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("de");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("de");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("El");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("a las");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        Hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00  ", "00:30  ", "01:00  ", "01:30  ", "02:00  ", "02:30  ", "03:00  ", "03:30  ", "04:00  ", "04:30  ", "05:00  ", "05:30  ", "06:00  ", "06:30  ", "07:00  ", "07:30  ", "08:00  ", "08:30  ", "09:00  ", "09:30  ", "10:00  ", "10:30  ", "11:00  ", "11:30  ", "12:00  ", "12:30  ", "13:00  ", "13:30  ", "14:00  ", "14:30  ", "15:00  ", "15:30  ", "16:00  ", "16:30  ", "17:00  ", "17:30  ", "18:00  ", "18:30  ", "19:00  ", "19:30  ", "20:00  ", "20:30  ", "21:00  ", "21:30  ", "22:00  ", "22:30  ", "23:00  ", "23:30  ", "24:00" }));
        getContentPane().add(Hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jScrollPane2.setViewportView(Listrab2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 100, 130));

        jScrollPane3.setViewportView(ListTrab1);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 100, 130));

        ElimTrab.setText("Eliminar");
        ElimTrab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElimTrabActionPerformed(evt);
            }
        });
        getContentPane().add(ElimTrab, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));

        AñadEstab.setText("Añadir");
        AñadEstab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadEstabActionPerformed(evt);
            }
        });
        getContentPane().add(AñadEstab, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 70, -1));

        jLabel3.setText("Establecimientos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel5.setText("Trabajos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        Estab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(Estab, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, -1));

        AñadTrab1.setText("Añadir");
        AñadTrab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadTrab1ActionPerformed(evt);
            }
        });
        getContentPane().add(AñadTrab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        dispose();
        Cliente C=new Cliente();
        C.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void DiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaActionPerformed

    private void AñadEstabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadEstabActionPerformed
        Añadir_Establecimiento AE= new Añadir_Establecimiento();
        AE.setVisible(true);
    }//GEN-LAST:event_AñadEstabActionPerformed

    private void AñadTrab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadTrab1ActionPerformed
        String Trab1,Trab2;
        int s=obList.size(),c = 0;
        String Trabs []= new String [s];
        Trab1=(String)ListTrab1.getSelectedValue();
        
        if(s>0){
            for(int i=0;i!=s;i++){
                Trab2=(String)obList.getElementAt(i);
                Trabs[i]=Trab2;
            }
            for(int i=0;i!=s;i++){
                if(Trabs[i].equals(Trab1))
                    c++;
            }
            if(c>0){
            }
            else
                obList.addElement(Trab1);
        }
        else{
            obList.addElement(Trab1);
        }
    }//GEN-LAST:event_AñadTrab1ActionPerformed

    private void ElimTrabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElimTrabActionPerformed
        int indice=Listrab2.getSelectedIndex();
        
        obList.remove(indice); 
    }//GEN-LAST:event_ElimTrabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedir_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedir_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedir_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedir_servicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedir_servicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadEstab;
    private javax.swing.JButton AñadTrab1;
    private javax.swing.JComboBox<String> Año;
    private javax.swing.JComboBox<String> Dia;
    private javax.swing.JButton ElimTrab;
    private javax.swing.JButton EnvServicio;
    private javax.swing.JComboBox<String> Estab;
    private javax.swing.JComboBox<String> Hora;
    private javax.swing.JList<String> ListTrab1;
    private javax.swing.JList<String> Listrab2;
    private javax.swing.JComboBox<String> Mes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
