/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofincurso;

import java.sql.*;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author DAW
 */
public class Registro extends javax.swing.JFrame {

    public Registro() {
        setLocation(700,400);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Nomtxt = new javax.swing.JTextField();
        Ap1txt = new javax.swing.JTextField();
        Ap2txt = new javax.swing.JTextField();
        DNItxt = new javax.swing.JTextField();
        Teltxt = new javax.swing.JTextField();
        CEtxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Trabajador = new javax.swing.JCheckBox();
        codEmptxt = new javax.swing.JTextField();
        btnReg = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Conttxt = new javax.swing.JPasswordField();
        repConttxt = new javax.swing.JPasswordField();
        btnVol = new javax.swing.JButton();
        btnSal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel2.setText("1º Apellido");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setText("DNI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel5.setText("Correo Electronico");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jLabel6.setText("Contraseña");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabel7.setText("Repetir contraseña");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));
        getContentPane().add(Nomtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 120, -1));
        getContentPane().add(Ap1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 120, -1));
        getContentPane().add(Ap2txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 120, -1));

        DNItxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNItxtActionPerformed(evt);
            }
        });
        getContentPane().add(DNItxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, -1));
        getContentPane().add(Teltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 120, -1));
        getContentPane().add(CEtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 120, -1));

        jLabel8.setText("2º Apellido (opcional)");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel11.setText("DATOS PERSONALES");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel12.setText("DATOS DE SESIÓN");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        Trabajador.setText("Trabajador");
        Trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrabajadorActionPerformed(evt);
            }
        });
        getContentPane().add(Trabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));
        getContentPane().add(codEmptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 120, -1));

        btnReg.setText("Terminar Registro");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });
        getContentPane().add(btnReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel9.setText("(Introduzca el codigo de su empresa)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));
        getContentPane().add(Conttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 120, -1));
        getContentPane().add(repConttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 120, -1));

        btnVol.setText("VOLVER");
        btnVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolActionPerformed(evt);
            }
        });
        getContentPane().add(btnVol, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        btnSal.setText("SALIR");
        btnSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalActionPerformed(evt);
            }
        });
        getContentPane().add(btnSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrabajadorActionPerformed

    private void btnVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolActionPerformed
        Inicio i= new Inicio();
        i.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVolActionPerformed

    private void btnSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalActionPerformed

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        ConectBD bd= new ConectBD();
        
        try{
            Connection c =DriverManager.getConnection("jdbc:mysql://localhost/limpieza", "JavierC","Arcoiris");
            
            String Nom,Ap1,Ap2,DNI,Tel,CE,codEmp,Con="";  
            char[] Cont,repCont;
            
            //preparamos el codigo de registro para ambos casos
            String T="INSERT INTO trabajadores VALUES (DNI,id_compañia,nombre,apellido1,apellido2,correo,contraseña,telefono) VALUES (?,1,?,?,?,?,?,?);";
            
  
            Nom=Nomtxt.getText();
            Ap1=Ap1txt.getText();
            Ap2=Ap2txt.getText();
            DNI=DNItxt.getText();
            Tel=Teltxt.getText();
            CE=CEtxt.getText();
            Cont=Conttxt.getPassword();
            repCont=repConttxt.getPassword();
            codEmp=codEmptxt.getText();
            
            //pasar contraseña a string
            for(int i=0;i<Cont.length;i++){
                Con=Con+Cont[i];
            }
            
            if(Trabajador.isSelected()){              
                Statement s = c.createStatement();
                ResultSet t= s.executeQuery("SELECT codigo FROM compañias WHERE codigo LIKE'"+codEmp+"'");             
                if(t.next()){
                    if((CE.trim().length()==0)||(Ap1.trim().length()==0)||(DNI.trim().length()==0)||(Tel.trim().length()==0)||(CE.trim().length()==0)||(Cont.length==0)||(repCont.length==0)||(codEmp.trim().length()==0)){
                    JOptionPane.showMessageDialog(null, "Porfavor rellene todos los campos");
                    }
                    else
                        if(Arrays.equals(Cont, repCont)==false){
                            JOptionPane.showMessageDialog(null, "La contraseña no coincide");
                        }
                    else{
                        int op=JOptionPane.showConfirmDialog(null,"¿Está seguro de los datos intoducidos?", "confirmación", 0);
                        if(op==0){//si
                            if(Ap2.trim().length()==0){//sin apellido2
                            s.executeUpdate("INSERT INTO trabajadores VALUES (DNI,id_compañia,nombre,apellido1,correo,contraseña,telefono) VALUES ('"+DNI+"',1,'"+Nom+"','"+Ap1+"','"+CE+"','"+Con+"',"+Tel+");");
                        }
                        else{
                            s.executeUpdate("INSERT INTO trabajadores VALUES (DNI,id_compañia,nombre,apellido1,apellido2,correo,contraseña,telefono) VALUES ('"+DNI+"',1,'"+Nom+"','"+Ap1+"','"+Ap2+"','"+CE+"','"+Con+"',"+Tel+");");
                        }
                            JOptionPane.showMessageDialog(null, "Registro exitoso");
                            dispose();
                            Inicio i=new Inicio();
                            i.setVisible(true);
                        }
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Codigo de empresa no valido");
                }
                
            }
            else{ //Cliente
                if((codEmp.trim().length()>0)){
                    JOptionPane.showMessageDialog(null, "si desea registrarse como cliente no es necesario un codigo de empresa");
                }
                if((CE.trim().length()==0)||(Ap1.trim().length()==0)||(DNI.trim().length()==0)||(Tel.trim().length()==0)||(CE.trim().length()==0)||(Cont.length==0)||(repCont.length==0)){
                    JOptionPane.showMessageDialog(null, "Porfavor rellene todos los campos");
                }
                else
                    if(Arrays.equals(Cont, repCont)==false){
                        JOptionPane.showMessageDialog(null, "La contraseña no coincide");
                    }
                else{
                    int op=JOptionPane.showConfirmDialog(null,"¿Está seguro de los datos intoducidos?", "confirmación", 0);
                    if(op==0){//si
                        Statement s = c.createStatement();
                        if(Ap2.trim().length()==0){//sin apellido2
                            s.executeUpdate("INSERT INTO clientes VALUES (DNI,nombre,apellido1,correo,contraseña,telefono) VALUES ('"+DNI+"','"+Nom+"','"+Ap1+"','"+CE+"','"+Con+"',"+Tel+");");
                        }
                        else{    
                            s.executeUpdate("INSERT INTO clientes VALUES (DNI,nombre,apellido1,apellido2,correo,contraseña,telefono) VALUES ('"+DNI+"','"+Nom+"','"+Ap1+"',"+Ap1+"','"+CE+"','"+Con+"',"+Tel+");");
                        }          
                        JOptionPane.showMessageDialog(null, "Registro exitoso");
                        dispose();
                        Inicio i=new Inicio();
                        i.setVisible(true);
                    }
                }
            }       
        }
        
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la BD");
        }
        
    }//GEN-LAST:event_btnRegActionPerformed

    private void DNItxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNItxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNItxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ap1txt;
    private javax.swing.JTextField Ap2txt;
    private javax.swing.JTextField CEtxt;
    private javax.swing.JPasswordField Conttxt;
    private javax.swing.JTextField DNItxt;
    private javax.swing.JTextField Nomtxt;
    private javax.swing.JTextField Teltxt;
    private javax.swing.JCheckBox Trabajador;
    private javax.swing.JButton btnReg;
    private javax.swing.JButton btnSal;
    private javax.swing.JButton btnVol;
    private javax.swing.JTextField codEmptxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField repConttxt;
    // End of variables declaration//GEN-END:variables
}
